config/routes.rb
Rails.application.routes.draw do

  get '/' => 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  delete '/logout' => 'sessions#destroy'
  get '/logout' => 'sessions#destroy'
  get '/auth/:provider/callback' => 'sessions#create'
  resources :reviews
  resources :beers do
    resources :reviews, only: [:new, :index]
  end
  
  resources :breweries, only: [:index, :show, :new, :create] do
    resources :beers, only: [:show, :index]
  end
  resources :users, only: [:new, :create, :show]
  # patch 'reviews/:id', to: 'reviews#update'
  # delete '/beers/:id', to: 'beer#destroy', as:'delete_beer'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  has_many :reviewed_beers, through: :reviews, source: :beer
  has_many :beers #that they created

  validates :username, uniqueness: true, presence: true
  has_secure_password

  def self.create_by_google_omniauth(auth)
    self.find_or_create_by(username: auth[:info][:email]) do |u|
      u.password = 'SecureRandom.hex'
    end
  end

  def self.create_by_github_omniauth(auth)
    self.find_or_create_by(username: auth[:info][:nickname]) do |u|
      u.password = SecureRandom.hex
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find_by_id(params[:id])
    redirect_to '/' if !@user
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<%= render partial: 'layouts/errors', locals: {object: @user}  %>

<h1>Sign Up!</h1>

<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %><br><br>

  <%= f.label :password %>
  <%= f.password_field :password %><br><br>

  <%= f.submit "Sign Up" %>
<% end %>

app/views/users/show.html.erb
Welcome <%= @user.username %>
<h3>Here are the beers reviewed by you!</h3>
<ul>
  <% @user.reviewed_beers.each do |b| %>
    <li><%= link_to b.name, beer_path(b) %></li>
  <%end %>
</ul>