config/routes.rb
Rails.application.routes.draw do

  get '/' => 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  delete '/logout' => 'sessions#destroy'
  get '/logout' => 'sessions#destroy'
  get '/auth/:provider/callback' => 'sessions#create'
  resources :reviews
  resources :beers do
    resources :reviews, only: [:new, :index]
  end
  
  resources :breweries, only: [:index, :show, :new, :create] do
    resources :beers, only: [:show, :index]
  end
  resources :users, only: [:new, :create, :show]
  # patch 'reviews/:id', to: 'reviews#update'
  # delete '/beers/:id', to: 'beer#destroy', as:'delete_beer'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/brewery.rb
class Brewery < ApplicationRecord
  has_many :beers
  has_many :reviews, through: :beers
  validates :name, presence: true, uniqueness: true
  validates :location, presence: true

  scope :alpha, -> {order(:name)}

  def name_and_location
    "#{name} - #{location}"
  end
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :redirect_if_not_logged_in
  before_action :set_brewery, only: [:show, :edit, :update]

  def index
    if params[:q]
      @breweries = Brewery.where("name like ?", "%#{params[:q]}%").alpha
    else
      @breweries = Brewery.alpha
    end
  end

  def new
    @brewery = Brewery.new
  end

  def show
  end

  def create
    if !!logged_in?
      @brewery = Brewery.create(brewery_params)

      if @brewery.save
        flash[:alert] = "Brewery created!"
        redirect_to brewery_path(@brewery)
      else
        render :new
      end
    else
      redirect_to login_path
    end
  end

  def edit
  end

  def update
    @brewery.update(brewery_params)
    if @brewery.save
      flash[:alert] = "Brewery updated"
      redirect_to brewery_path(@brewery)
    else
      render :edit
    end
  end

  private

  def brewery_params
     params.require(:brewery).permit(:name, :location)
  end

  def set_brewery
    @brewery = Brewery.find_by_id(params[:id])
  end

end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_form.html.erb
<%= form_for @brewery do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br><br>

  <%= f.label :location %>
  <%= f.text_field :location %><br><br>

  <%= f.submit "Submit Brewery Info" %>
<% end %>

app/views/breweries/edit.html.erb
<h1>Edit Info for <%= @brewery.name %></h1>
<%= render partial: 'form' %>

app/views/breweries/index.html.erb
<h1> All Breweries </h1>
<%= render partial: 'layouts/search', locals: {object_path: breweries_path}  %>

<%= link_to "Create New Brewery", new_brewery_path %>

<% @breweries.each do |brewery| %>
  <h2><%= link_to brewery.name_and_location, brewery_beers_path(brewery) %></h2>
<% end %>

app/views/breweries/new.html.erb
<h1>Register a Brewery:</h1>
 <%= render partial: 'layouts/errors', locals: {object: @brewery}  %>
 <%= render partial: 'layouts/flash' %>
 <%= render partial: 'form' %>

app/views/breweries/show.html.erb
<%= render partial: 'layouts/flash'  %>

<%= @brewery.name_and_location %>