config/routes.rb
Rails.application.routes.draw do

  get '/' => 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  delete '/logout' => 'sessions#destroy'
  get '/logout' => 'sessions#destroy'
  get '/auth/:provider/callback' => 'sessions#create'
  resources :reviews
  resources :beers do
    resources :reviews, only: [:new, :index]
  end
  
  resources :breweries, only: [:index, :show, :new, :create] do
    resources :beers, only: [:show, :index]
  end
  resources :users, only: [:new, :create, :show]
  # patch 'reviews/:id', to: 'reviews#update'
  # delete '/beers/:id', to: 'beer#destroy', as:'delete_beer'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/beer.rb
class Beer < ApplicationRecord
  belongs_to :brewery
  belongs_to :user #creator
  has_many :reviews
  has_many :users, through: :reviews #user who reviewed
  has_one_attached :image
  validates :name, presence: true
  validates :style, presence: true
  validates :abv, presence: true
  validates :flavor_profile, presence: true
  validates :brewery, presence: true
  validate :not_a_duplicate, on: :create

  scope :order_by_rating, -> {left_joins(:reviews).group(:id).order('avg(stars) desc')}

  def self.alpha
    order(:name)
  end

  def brewery_attributes=(attributes)
    self.brewery = Brewery.find_or_create_by(attributes) if !attributes['name'].empty?
    self.brewery
  end

  def not_a_duplicate
    if Beer.find_by(name: name, brewery_id: brewery_id)
      errors.add(:name, 'has already been added for that brewery')
    end
  end

  def name_and_brewery
    "#{name} - #{brewery.name}"
  end

end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :set_beer, only: [:show, :edit, :update]
  before_action :redirect_if_not_logged_in

  def new
    @beer = Beer.new
    @beer.build_brewery
    flash[:alert] = "If you wish to create a new brewery select Create New Brewery from dropdown."
  end

  def create
    if !!logged_in?
      @beer = Beer.create(beer_params)
      @beer.user_id = session[:user_id]

      if @beer.save
        # @beer.image.purge
        @beer.image.attach(params[:image])
        flash[:alert] = "Beer created!"
        redirect_to beer_path(@beer)
      else
        @beer.build_brewery
        render :new
      end
    else
      redirect_to login_path
    end
  end

  def show
  end

  def edit
    if current_user != @beer.user
      flash[:alert] = "Only the creator of a beer can edit its details"
      redirect_to beer_path(@beer)
    else
      flash[:alert] = "If you wish to create a new brewery select Create New Brewery from dropdown."
    end
  end

  def index
    if params[:q]
      if !params[:brewery_id]
        @beers = Beer.where("name like ?", "%#{params[:q]}%")
      else
        @brewery = Brewery.find_by_id(params[:brewery_id])
        @beers = Beer.where("brewery_id like ? and name like ?", params[:brewery_id], "%#{params[:q]}%")
      end
    else
      if params[:brewery_id]
        @brewery = Brewery.find_by_id(params[:brewery_id])
        @beers = Beer.where(brewery_id: params[:brewery_id]).order_by_rating
      else
        @beers = Beer.order_by_rating.includes(:brewery)
      end
    end
  end

  def update
    @beer.image.purge
    @beer.image.attach(params[:image])
    if params[:brewery_id]
      @beer.update(beer_update_params)
    else
      @beer.update(beer_params)
    end

    if @beer.save
      flash[:alert] = "Beer updated"
      redirect_to beer_path(@beer)
    else
      render :edit
    end
  end

  def destroy
    Beer.find(params[:id]).destroy
    redirect_to beers_path
  end


  private

    def beer_params
       params.require(:beer).permit(:name, :style, :abv, :flavor_profile, :image, :brewery_id, brewery_attributes:[:name, :location])
    end

    def beer_update_params
      params.require(:beer).permit(:name, :style, :abv, :flavor_profile, :image, :brewery_id)
    end

    def set_beer
      @beer = Beer.find_by_id(params[:id])
      @brewery = @beer.brewery
      redirect_to beers_path if !@beer
    end
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/_form.html.erb
<%= form_for @beer do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %><br><br>
  </div>
  <div>
    <%= f.label :style %>
    <%= f.text_field :style %><br><br>
  </div>
  <div>
    <%= f.label :abv %>
    <%= f.text_field :abv %>%<br><br>
  </div>
  <div>
    <%= f.label :flavor_profile %><br>
    <%= f.text_area :flavor_profile %><br><br>
  </div>

  <p> Select a Brewery: </p>
  <div>
    <%= f.collection_select :brewery_id, Brewery.all, :id, :name_and_location, include_blank: 'Create New Brewery' %>
  </div>


  <div>
    <p> Or Create One: </p>
    <%= f.fields_for :brewery do |b| %>
      <%= b.label :name %>
      <%= b.text_field :name %>
      <%= b.label :location %>
      <%= b.text_field :location %>
    <% end %>
  </div><br>

  <div>
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div><br>

<%= f.submit %>
<% end %>

app/views/beers/edit.html.erb
<h1>Edit info for <%= @beer.name %></h1>
<%= render partial: 'layouts/errors', locals: {object: @beer} %>
<%= render partial: 'layouts/flash' %>
<%= render partial: 'form' %>

app/views/beers/index.html.erb
<h1> All Beers
<% if @brewery %>
  by <%= @brewery.name %>
  <% which_beer = brewery_beers_path(@brewery) %>
<% else %>
  <% which_beer = beers_path %>
<% end %></h1>

<%= render partial: 'layouts/search', locals: {object_path: which_beer}  %>

<% @beers.each do |beer| %>
    <h2 id='beername'><%= link_to beer.name, beer_path(beer.id) %> - <%= beer.abv %>%, by <%= beer.brewery.name %></h2>
    <%= link_to "Write a review", new_beer_review_path(beer.id) %>
    <% if beer.reviews.length > 0 %>
      <%= link_to "See all reviews", beer_reviews_path(beer.id) %>
    <% end %>
  <div>
    <p><%= beer.flavor_profile %></p>
  </div>
<% end %>

app/views/beers/new.html.erb
<h1>Create New Beer</h1>

<%= render partial: 'layouts/errors', locals: {object: @beer}  %>
<%= render partial: 'form' %>

app/views/beers/show.html.erb
<%= render partial: 'layouts/flash'  %>

<h1><%= @beer.name %>  </h1>

<h2>by <%= @beer.brewery.name %> </h2>
<div>
  <p><%= @beer.flavor_profile %></p>
  <p> <%= image_tag @beer.image if @beer.image.attached? %> </p>
</div>

<%= form_tag beer_path(@beer.id), method: "delete" do %>
  <%= submit_tag "Delete #{@beer.name}" %>
<% end %>