config/routes.rb
Rails.application.routes.draw do

  get '/' => 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  delete '/logout' => 'sessions#destroy'
  get '/logout' => 'sessions#destroy'
  get '/auth/:provider/callback' => 'sessions#create'
  resources :reviews
  resources :beers do
    resources :reviews, only: [:new, :index]
  end
  
  resources :breweries, only: [:index, :show, :new, :create] do
    resources :beers, only: [:show, :index]
  end
  resources :users, only: [:new, :create, :show]
  # patch 'reviews/:id', to: 'reviews#update'
  # delete '/beers/:id', to: 'beer#destroy', as:'delete_beer'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

     <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<p class="alert">
<% flash.each do |k, v| %>
<%= v %>
<% end %></p>

app/views/layouts/_loggedin_links.html.erb
<%= link_to "Home", user_path(current_user) %>
<%= link_to "Add a New Beer", new_beer_path %>
<%= link_to "All Beers", beers_path %>
<%= link_to "Add a Review", new_review_path %>
<%= link_to "All Reviews", reviews_path %>
<%= link_to "All Breweries", breweries_path %>
<%= link_to "Log Out", logout_path, method: :delete %>

app/views/layouts/_loggedout_links.html.erb
<%= link_to "Login", login_path %>
<%= link_to "Signup", signup_path %>
<%= link_to "Sign in with Google", "/auth/google_oauth2" %>

app/views/layouts/_search.html.erb
<%= form_with(url: object_path, method: 'get') do %>
  <%= label_tag(:q, "Search for") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeerSnobsRuby</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <div>
    <%= render_nav_bar %>
  </div>

  <body>
    <%= yield %>
  </body>
</html>